steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lead-discovery-backend', '-f', 'backend/Dockerfile', '.']
    dir: '.'

images:
  - 'gcr.io/$PROJECT_ID/lead-discovery-backend'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

